### PR TITLE
built middleware for authentication and implemented it to protect all…

### PR DESCRIPTION
**Pull request by Emekarr**
… the routes with auth

### CODE REVIEW

**Comment by eni4sure** [comment]
How do I confirm this works?

**Comment by Emekarr** [comment]
> How do I confirm this works?

Fork the dev branch from my repo 

> How do I confirm this works?

Pull the dev branch from the forked repo on my account and run and test locally.

**Comment by Emekarr** [comment]
> How do I confirm this works?

Pull the dev branch from the forked repo on my account and run and test locally.

**Comment by eni4sure** [comment]
alright great!
But I can't merge this now because frontend still need to do a lot of testing and all
and this could be a blocker

**Comment by Emekarr** [comment]
> alright great! But I can't merge this now because frontend still need to do a lot of testing and all and this could be a blocker

Sure. But try to inform them that when it's made every request will be blocked if they do not submit a Bearer token.

**Review by eni4sure — APPROVED** [review]

**Pull request merged**
