### PR TITLE
fixed delayed action on piece move

### PR DESCRIPTION
**Pull request by otutukingsley**
Made the chess pieces react instantly, instead of the delayed reaction currently in place

### CODE REVIEW

**Comment by NdubuisiJr** [comment]
@eni4sure have you seen this?

**Comment by NdubuisiJr** [comment]
@odizee have you seen this?

**Comment by eni4sure** [comment]
Seeing it now boss
@otutukingsley please fix merge conflicts first

Also why so many file changes 🌚

**Comment by eni4sure** [comment]
I'll also have to close this PR the code here is very outdated 
Kindly pull from upstream dev to update it

**Comment by odizee** [comment]
I've informed him. Earlier on.

**Pull request closed without merging**
