### PR TITLE
Implemented versioning (/api/v1/)

### PR DESCRIPTION
**Pull request by NdubuisiJr**
@eni4sure and @Alao-Abiodun, please review

### CODE REVIEW

**Comment by eni4sure** [comment]
looks good, but let's still take a chill on this boss!
SInce people are still making changes right now
to reduce merge conflicts issues

**Comment by eni4sure** [comment]
I'll close this now

**Comment by NdubuisiJr** [comment]
Bro don’t close it…
API versioning is very important and it doesn’t do too much.

this will be merged once after all the assigned endpoints have been implemented.

**Comment by NdubuisiJr** [comment]
This is the only “easy” time we have to implement it. Because, if the frontend integrates without proper versioning of the backend, it will be very difficult to change it later.

**Comment by eni4sure** [comment]
yess boss, i was saying you can re-open it after the routes have been completed, which means you'll also have to add the created routes to the version folder too

That's why I closed it.
To also not allow unreviewed PRs pending 🙂

**Pull request merged**
