### PR TITLE
Updated Homepage to reflect new design

### PR DESCRIPTION
**Pull request by vermilion4**
Screenshot (254)

### CODE REVIEW

**Comment by eni4sure** [comment]
@Babsmutini @odizee 
can this be merged please?

**Comment by odizee** [comment]
> @Babsmutini @odizee
> can this be merged please?

The update is not necessary. Na to delete am o

**Comment by eni4sure** [comment]
ahan it looks nicer na
at least as far as it's not breaking anything

Let's merge it, so we can have a new look
also it states "updated homepage to reflect the design" 

so still looks necessary @odizee

**Comment by odizee** [comment]
> ahan it looks nicer na
> at least as far as it's not breaking anything
> 
> Let's merge it, so we can have a new look
> also it states "updated homepage to reflect the design"
> 
> so still looks necessary @odizee

I think the heading is to come from zuri main.

**Comment by odizee** [comment]
Okay. Designers said it's we are to implement the heading. Merging in 5, 4, 3...

**Comment by eni4sure** [comment]
Thanks boss!
Love the new look! ⭐

**Comment by odizee** [comment]
Welcome sir

**Comment by vermilion4** [comment]
> Thanks boss!
> Love the new look! ⭐

👍👍

**Comment by vermilion4** [comment]
> Welcome sir

Oga odiri... thank you for merging oo

**Pull request merged**
