### PR TITLE
Created the chats section for spectators while viewing an on-going game.

### PR DESCRIPTION
**Pull request by Yemi-dev**
FDF48327-8B78-4D54-8B08-DD85EE779790
74C33BB2-B2BC-41BA-96CF-EB2597E83CA7
#359 
worked on the chats system issue

### CODE REVIEW

**Comment by eni4sure** [comment]
@Yemi-dev kindly fix the merge conflicts

CC: @Babsmutini @odizee 
Review please
this PR has been open

**Comment by odizee** [comment]
Fix conflits and 

> @Yemi-dev kindly fix the merge conflicts
> 
> CC: @Babsmutini @odizee
> Review please
> this PR has been open

I Have told her. I will remind her again.

**Comment by Yemi-dev** [comment]
> @Yemi-dev kindly fix the merge conflicts
> 
> CC: @Babsmutini @odizee
> Review please
> this PR has been open

>is it still conflicting?

**Comment by Yemi-dev** [comment]
> Fix conflits and
> 
> > @Yemi-dev kindly fix the merge conflicts
> > CC: @Babsmutini @odizee
> > Review please
> > this PR has been open
> 
> I Have told her. I will remind her again.

>please check, is it still conflicting....?

**Comment by eni4sure** [comment]
would be reviewed shortly @Yemi-dev

**Comment by eni4sure** [comment]
@Yemi-dev one last merge conflict to resolve 🙏🏾

**Comment by Babsmutini** [comment]
There is still a conflict

**Comment by Yemi-dev** [comment]
I don’t even know what went wrong like this.
I’d try something again

**Comment by eni4sure** [comment]
No no just fix this last one @Yemi-dev 
A PR was just merged to fix an issue, that's what brought up a conflict with yours

**Comment by Yemi-dev** [comment]
Ah🥴….I’ve deleted my repo….want to do it afresh… thought I was the problem

**Comment by eni4sure** [comment]
ahhhhhh 😭😭😭
@Yemi-dev so sorry 😞

**Comment by Yemi-dev** [comment]
I have opened a new PR

**Pull request closed without merging**
